# Change variable names
new_names = {'darchsn': 'ID',
             'age1115': 'age',
             'dgtdcan': 'triedcan',
             'dgtdamp': 'triedamp',
             'dgtdlsd': 'triedlsd',
             'dgtdecs': 'triedecstasy',
             'dgtdsem': 'triedsem',
             'dgtdpop': 'triedpops',
             'dgtdtrn': 'triedtranq',
             'dgtdher': 'triedheroin',
             'dgtdmsh': 'triedmush',
             'dgtdmth': 'triedmeth',
             'dgtdcrk': 'triedcrack',
             'dgtdcok': 'triedcoke',
             'dgtdket': 'triedket',
             'dgtdmph': 'triedmeph',
             'dgtdnox': 'triednox',
             'dgtdleg': 'triedleg',
             'devrstm': 'everstim',
             'devrpsy': 'everpsycdel',
             'devropi': 'everopiate',
             'devrcla': 'everclassA',
             'devrrps': 'everpsycact',
             'ddgany': 'anydrugs'}